workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Expo CLI
        script: npm install -g expo-cli
      - name: Build iOS
        script: expo build:ios
    artifacts:
      - build/*.ipa