workflows:
  expo-ios-simulator:
    name: Expo iOS Simulator Build
    max_build_duration: 60
    environment:
      node: 18.15.0
      xcode: latest
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI and EAS CLI
        script: |
          npm install -g expo-cli@latest eas-cli@latest
      - name: Check Expo environment
        script: |
          npx expo-doctor
          npx expo-env-info
      - name: Build iOS for Simulator
        script: |
          npx eas-cli build --platform ios --profile preview --non-interactive --local
    artifacts:
      - build/*.tar.gz