workflows:
  expo-ios:
     name: Expo iOS Workflow
     max_build_duration: 60
     environment:
         node: latest
         xcode: latest
     scripts:
        - name: Install dependencies
          script: |
            npm install
        - name: Install Expo Cli
          script: |
            npm install -g expo-cli
        - name: Build iOS
          script: |
            expo build:ios --non-interactive
      artifacts:
        - build/*
        
