workflows:
  expo-ios:
    name: Expo iOS Workflow
    max_build_duration: 60
    environment:
      node: 18.15.0  # Especificamos una versión de Node.js compatible
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli@latest
          npm install -g eas-cli@latest
      - name: Check Expo environment
        script: |
          npx expo-doctor
          npx expo-env-info
      - name: Build iOS
        script: |
          npx eas-cli build --platform ios --non-interactive
    artifacts:
      - build/*